---
installer_cache_dir: "{{ lookup('env', 'HOME') }}/.cache/ocp-cluster-lifecycle"
openshift_install_bin: ""
openshift_mirror_base: "https://mirror.openshift.com/pub/openshift-v4"
# Cluster target arch drives which clients/ tree to use (default x86_64)
aws_architecture: x86_64
